<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Countrie\CountrieModels;
use App\Models\FullCountriesModels\FullCountrieModels;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        FullCountrieModels::truncate();


        $countries_data = [
            ['country_code' => 'CI', 'countrie_name' => 'Côte d\'Ivoire', 'phone_code' => '+225', 'flag' => '🇨🇮', 'currency' => 'XOF'],
            ['country_code' => 'BF', 'countrie_name' => 'Burkina Faso', 'phone_code' => '+226', 'flag' => '🇧🇫', 'currency' => 'XOF'],
            ['country_code' => 'ML', 'countrie_name' => 'Mali', 'phone_code' => '+223', 'flag' => '🇲🇱', 'currency' => 'Franc CFA'],
            ['country_code' => 'NE', 'countrie_name' => 'Niger', 'phone_code' => '+227', 'flag' => '🇳🇪', 'currency' => 'Franc CFA'],
            ['country_code' => 'US', 'countrie_name' => 'États-Unis', 'phone_code' => '+1', 'flag' => '🇺🇸', 'currency' => 'USD'],
            ['country_code' => 'CA', 'countrie_name' => 'Canada', 'phone_code' => '+1', 'flag' => '🇨🇦', 'currency' => 'CAD'],
            ['country_code' => 'AF', 'countrie_name' => 'Afghanistan', 'phone_code' => '+93', 'flag' => '🇦🇫', 'currency' => 'AFN'],
            ['country_code' => 'AL', 'countrie_name' => 'Albanie', 'phone_code' => '+355', 'flag' => '🇦🇱', 'currency' => 'ALL'],
            ['country_code' => 'DZ', 'countrie_name' => 'Algérie', 'phone_code' => '+213', 'flag' => '🇩🇿', 'currency' => 'DZD'],
            ['country_code' => 'AS', 'countrie_name' => 'Samoa américaines', 'phone_code' => '+1684', 'flag' => '🇦🇸', 'currency' => 'USD'],
            ['country_code' => 'AD', 'countrie_name' => 'Andorre', 'phone_code' => '+376', 'flag' => '🇦🇩', 'currency' => 'EUR'],
            ['country_code' => 'AO', 'countrie_name' => 'Angola', 'phone_code' => '+244', 'flag' => '🇦🇴', 'currency' => 'AOA'],
            ['country_code' => 'AI', 'countrie_name' => 'Anguilla', 'phone_code' => '+1264', 'flag' => '🇦🇮', 'currency' => 'XCD'],
            ['country_code' => 'AQ', 'countrie_name' => 'Antarctique', 'phone_code' => '+672', 'flag' => '🇦🇶', 'currency' => 'AUD'],
            ['country_code' => 'AG', 'countrie_name' => 'Antigua-et-Barbuda', 'phone_code' => '+1268', 'flag' => '🇦🇬', 'currency' => 'XCD'],
            ['country_code' => 'AR', 'countrie_name' => 'Argentine', 'phone_code' => '+54', 'flag' => '🇦🇷', 'currency' => 'ARS'],
            ['country_code' => 'AM', 'countrie_name' => 'Arménie', 'phone_code' => '+374', 'flag' => '🇦🇲', 'currency' => 'AMD'],
            ['country_code' => 'AW', 'countrie_name' => 'Aruba', 'phone_code' => '+297', 'flag' => '🇦🇼', 'currency' => 'AWG'],
            ['country_code' => 'AU', 'countrie_name' => 'Australie', 'phone_code' => '+61', 'flag' => '🇦🇺', 'currency' => 'AUD'],
            ['country_code' => 'AT', 'countrie_name' => 'Autriche', 'phone_code' => '+43', 'flag' => '🇦🇹', 'currency' => 'EUR'],
            ['country_code' => 'AZ', 'countrie_name' => 'Azerbaïdjan', 'phone_code' => '+994', 'flag' => '🇦🇿', 'currency' => 'AZN'],
            ['country_code' => 'BS', 'countrie_name' => 'Bahamas', 'phone_code' => '+1242', 'flag' => '🇧🇸', 'currency' => 'BSD'],
            ['country_code' => 'BH', 'countrie_name' => 'Bahreïn', 'phone_code' => '+973', 'flag' => '🇧🇭', 'currency' => 'BHD'],
            ['country_code' => 'BD', 'countrie_name' => 'Bangladesh', 'phone_code' => '+880', 'flag' => '🇧🇩', 'currency' => 'BDT'],
            ['country_code' => 'BB', 'countrie_name' => 'Barbade', 'phone_code' => '+1246', 'flag' => '🇧🇧', 'currency' => 'BBD'],
            ['country_code' => 'BY', 'countrie_name' => 'Bélarus', 'phone_code' => '+375', 'flag' => '🇧🇾', 'currency' => 'BYN'],
            ['country_code' => 'BE', 'countrie_name' => 'Belgique', 'phone_code' => '+32', 'flag' => '🇧🇪', 'currency' => 'EUR'],
            ['country_code' => 'BZ', 'countrie_name' => 'Belize', 'phone_code' => '+501', 'flag' => '🇧🇿', 'currency' => 'BZD'],
            ['country_code' => 'BJ', 'countrie_name' => 'Bénin', 'phone_code' => '+229', 'flag' => '🇧🇯', 'currency' => 'XOF'],
            ['country_code' => 'BT', 'countrie_name' => 'Bhoutan', 'phone_code' => '+975', 'flag' => '🇧🇹', 'currency' => 'BTN'],
            ['country_code' => 'BO', 'countrie_name' => 'Bolivie', 'phone_code' => '+591', 'flag' => '🇧🇴', 'currency' => 'BOB'],
            ['country_code' => 'BA', 'countrie_name' => 'Bosnie-Herzégovine', 'phone_code' => '+387', 'flag' => '🇧🇦', 'currency' => 'BAM'],
            ['country_code' => 'BW', 'countrie_name' => 'Botswana', 'phone_code' => '+267', 'flag' => '🇧🇼', 'currency' => 'BWP'],
            ['country_code' => 'BR', 'countrie_name' => 'Brésil', 'phone_code' => '+55', 'flag' => '🇧🇷', 'currency' => 'BRL'],
            ['country_code' => 'BN', 'countrie_name' => 'Brunei Darussalam', 'phone_code' => '+673', 'flag' => '🇧🇳', 'currency' => 'BND'],
            ['country_code' => 'BG', 'countrie_name' => 'Bulgarie', 'phone_code' => '+359', 'flag' => '🇧🇬', 'currency' => 'BGN'],
            ['country_code' => 'BI', 'countrie_name' => 'Burundi', 'phone_code' => '+257', 'flag' => '🇧🇮', 'currency' => 'BIF'],
            ['country_code' => 'KH', 'countrie_name' => 'Cambodge', 'phone_code' => '+855', 'flag' => '🇰🇭', 'currency' => 'KHR'],
            ['country_code' => 'CM', 'countrie_name' => 'Cameroun', 'phone_code' => '+237', 'flag' => '🇨🇲', 'currency' => 'XAF'],
            ['country_code' => 'CV', 'countrie_name' => 'Cap-Vert', 'phone_code' => '+238', 'flag' => '🇨🇻', 'currency' => 'CVE'],
            ['country_code' => 'KY', 'countrie_name' => 'Îles Caïmans', 'phone_code' => '+1345', 'flag' => '🇰🇾', 'currency' => 'KYD'],
            ['country_code' => 'CF', 'countrie_name' => 'République centrafricaine', 'phone_code' => '+236', 'flag' => '🇨🇫', 'currency' => 'XAF'],
            ['country_code' => 'TD', 'countrie_name' => 'Tchad', 'phone_code' => '+235', 'flag' => '🇹🇩', 'currency' => 'XAF'],
            ['country_code' => 'CL', 'countrie_name' => 'Chili', 'phone_code' => '+56', 'flag' => '🇨🇱', 'currency' => 'CLP'],
            ['country_code' => 'CN', 'countrie_name' => 'Chine', 'phone_code' => '+86', 'flag' => '🇨🇳', 'currency' => 'CNY'],
            ['country_code' => 'CO', 'countrie_name' => 'Colombie', 'phone_code' => '+57', 'flag' => '🇨🇴', 'currency' => 'COP'],
            ['country_code' => 'KM', 'countrie_name' => 'Comores', 'phone_code' => '+269', 'flag' => '🇰🇲', 'currency' => 'KMF'],
            ['country_code' => 'CG', 'countrie_name' => 'Congo', 'phone_code' => '+242', 'flag' => '🇨🇬', 'currency' => 'CDF'],
            ['country_code' => 'CD', 'countrie_name' => 'République Démocratique du Congo', 'phone_code' => '+243', 'flag' => '🇨🇩', 'currency' => 'CDF'],
            ['country_code' => 'CK', 'countrie_name' => 'Îles Cook', 'phone_code' => '+682', 'flag' => '🇨🇰', 'currency' => 'NZD'],
            ['country_code' => 'CR', 'countrie_name' => 'Costa Rica', 'phone_code' => '+506', 'flag' => '🇨🇷', 'currency' => 'CRC'],
            ['country_code' => 'HR', 'countrie_name' => 'Croatie', 'phone_code' => '+385', 'flag' => '🇭🇷', 'currency' => 'HRK'],
            ['country_code' => 'CU', 'countrie_name' => 'Cuba', 'phone_code' => '+53', 'flag' => '🇨🇺', 'currency' => 'CUP'],
            ['country_code' => 'CY', 'countrie_name' => 'Chypre', 'phone_code' => '+357', 'flag' => '🇨🇾', 'currency' => 'EUR'],
            ['country_code' => 'CZ', 'countrie_name' => 'République tchèque', 'phone_code' => '+420', 'flag' => '🇨🇿', 'currency' => 'CZK'],
            ['country_code' => 'DK', 'countrie_name' => 'Danemark', 'phone_code' => '+45', 'flag' => '🇩🇰', 'currency' => 'DKK'],
            ['country_code' => 'DJ', 'countrie_name' => 'Djibouti', 'phone_code' => '+253', 'flag' => '🇩🇯', 'currency' => 'DJF'],
            ['country_code' => 'DM', 'countrie_name' => 'Dominique', 'phone_code' => '+1767', 'flag' => '🇩🇲', 'currency' => 'XCD'],
            ['country_code' => 'DO', 'countrie_name' => 'République Dominicaine', 'phone_code' => '+1', 'flag' => '🇩🇴', 'currency' => 'DOP'],
            ['country_code' => 'EC', 'countrie_name' => 'Équateur', 'phone_code' => '+593', 'flag' => '🇪🇨', 'currency' => 'USD'],
            ['country_code' => 'EG', 'countrie_name' => 'Égypte', 'phone_code' => '+20', 'flag' => '🇪🇬', 'currency' => 'EGP'],
            ['country_code' => 'SV', 'countrie_name' => 'Salvador', 'phone_code' => '+503', 'flag' => '🇸🇻', 'currency' => 'SVC'],
            ['country_code' => 'GQ', 'countrie_name' => 'Guinée équatoriale', 'phone_code' => '+240', 'flag' => '🇬🇶', 'currency' => 'GNF'],
            ['country_code' => 'ER', 'countrie_name' => 'Érythrée', 'phone_code' => '+291', 'flag' => '🇪🇷', 'currency' => 'ERN'],
            ['country_code' => 'EE', 'countrie_name' => 'Estonie', 'phone_code' => '+372', 'flag' => '🇪🇪', 'currency' => 'EUR'],
            ['country_code' => 'SZ', 'countrie_name' => 'Eswatini', 'phone_code' => '+268', 'flag' => '🇸🇿', 'currency' => 'SZL'],
            ['country_code' => 'ET', 'countrie_name' => 'Éthiopie', 'phone_code' => '+251', 'flag' => '🇪🇹', 'currency' => 'ETB'],
            ['country_code' => 'FI', 'countrie_name' => 'Finlande', 'phone_code' => '+358', 'flag' => '🇫🇮', 'currency' => 'EUR'],
            ['country_code' => 'FJ', 'countrie_name' => 'Fidji', 'phone_code' => '+679', 'flag' => '🇫🇯', 'currency' => 'FJD'],
            ['country_code' => 'FM', 'countrie_name' => 'Micronésie', 'phone_code' => '+691', 'flag' => '🇫🇲', 'currency' => 'USD'],
            ['country_code' => 'FR', 'countrie_name' => 'France', 'phone_code' => '+33', 'flag' => '🇫🇷', 'currency' => 'EUR'],
            ['country_code' => 'GA', 'countrie_name' => 'Gabon', 'phone_code' => '+241', 'flag' => '🇬🇦', 'currency' => 'XAF'],
            ['country_code' => 'GB', 'countrie_name' => 'Royaume-Uni', 'phone_code' => '+44', 'flag' => '🇬🇧', 'currency' => 'GBP'],
            ['country_code' => 'GE', 'countrie_name' => 'Géorgie', 'phone_code' => '+995', 'flag' => '🇬🇪', 'currency' => 'GEL'],
            ['country_code' => 'GH', 'countrie_name' => 'Ghana', 'phone_code' => '+233', 'flag' => '🇬🇭', 'currency' => 'GHS'],
            ['country_code' => 'GR', 'countrie_name' => 'Grèce', 'phone_code' => '+30', 'flag' => '🇬🇷', 'currency' => 'EUR'],
            ['country_code' => 'GD', 'countrie_name' => 'Grenade', 'phone_code' => '+1473', 'flag' => '🇬🇩', 'currency' => 'XCD'],
            ['country_code' => 'GT', 'countrie_name' => 'Guatemala', 'phone_code' => '+502', 'flag' => '🇬🇹', 'currency' => 'GTQ'],
            ['country_code' => 'GN', 'countrie_name' => 'Guinée', 'phone_code' => '+224', 'flag' => '🇬🇳', 'currency' => 'GNF'],
            ['country_code' => 'GW', 'countrie_name' => 'Guinée-Bissau', 'phone_code' => '+245', 'flag' => '🇬🇼', 'currency' => 'GNF'],
            ['country_code' => 'GY', 'countrie_name' => 'Guyana', 'phone_code' => '+592', 'flag' => '🇬🇾', 'currency' => 'GYD'],
            ['country_code' => 'HT', 'countrie_name' => 'Haïti', 'phone_code' => '+509', 'flag' => '🇭🇹', 'currency' => 'HTG'],
            ['country_code' => 'HN', 'countrie_name' => 'Honduras', 'phone_code' => '+504', 'flag' => '🇭🇳', 'currency' => 'HNL'],
            ['country_code' => 'HU', 'countrie_name' => 'Hongrie', 'phone_code' => '+36', 'flag' => '🇭🇺', 'currency' => 'HUF'],
            ['country_code' => 'IS', 'countrie_name' => 'Islande', 'phone_code' => '+354', 'flag' => '🇮🇸', 'currency' => 'ISK'],
            ['country_code' => 'IN', 'countrie_name' => 'Inde', 'phone_code' => '+91', 'flag' => '🇮🇳', 'currency' => 'INR'],
            ['country_code' => 'ID', 'countrie_name' => 'Indonésie', 'phone_code' => '+62', 'flag' => '🇮🇩', 'currency' => 'IDR'],
            ['country_code' => 'IR', 'countrie_name' => 'Iran', 'phone_code' => '+98', 'flag' => '🇮🇷', 'currency' => 'IRR'],
            ['country_code' => 'IQ', 'countrie_name' => 'Irak', 'phone_code' => '+964', 'flag' => '🇮🇶', 'currency' => 'IQD'],
            ['country_code' => 'IE', 'countrie_name' => 'Irlande', 'phone_code' => '+353', 'flag' => '🇮🇪', 'currency' => 'EUR'],
            ['country_code' => 'IL', 'countrie_name' => 'Israël', 'phone_code' => '+972', 'flag' => '🇮🇱', 'currency' => 'ILS'],
            ['country_code' => 'IT', 'countrie_name' => 'Italie', 'phone_code' => '+39', 'flag' => '🇮🇹', 'currency' => 'EUR'],
            ['country_code' => 'JM', 'countrie_name' => 'Jamaïque', 'phone_code' => '+1876', 'flag' => '🇯🇲', 'currency' => 'JMD'],
            ['country_code' => 'JP', 'countrie_name' => 'Japon', 'phone_code' => '+81', 'flag' => '🇯🇵', 'currency' => 'JPY'],
            ['country_code' => 'JO', 'countrie_name' => 'Jordanie', 'phone_code' => '+962', 'flag' => '🇯🇴', 'currency' => 'JOD'],
            ['country_code' => 'KZ', 'countrie_name' => 'Kazakhstan', 'phone_code' => '+7', 'flag' => '🇰🇿', 'currency' => 'KZT'],
            ['country_code' => 'KE', 'countrie_name' => 'Kenya', 'phone_code' => '+254', 'flag' => '🇰🇪', 'currency' => 'KES'],
            ['country_code' => 'KI', 'countrie_name' => 'Kiribati', 'phone_code' => '+686', 'flag' => '🇰🇮', 'currency' => 'AUD'],
            ['country_code' => 'KW', 'countrie_name' => 'Koweït', 'phone_code' => '+965', 'flag' => '🇰🇼', 'currency' => 'KWD'],
            ['country_code' => 'KG', 'countrie_name' => 'Kirghizistan', 'phone_code' => '+996', 'flag' => '🇰🇬', 'currency' => 'KGS'],
            ['country_code' => 'LA', 'countrie_name' => 'République Démocratique Populaire Lao', 'phone_code' => '+856', 'flag' => '🇱🇦', 'currency' => 'LAK'],
            ['country_code' => 'LV', 'countrie_name' => 'Lettonie', 'phone_code' => '+371', 'flag' => '🇱🇻', 'currency' => 'EUR'],
            ['country_code' => 'LB', 'countrie_name' => 'Liban', 'phone_code' => '+961', 'flag' => '🇱🇧', 'currency' => 'LBP'],
            ['country_code' => 'LS', 'countrie_name' => 'Lesotho', 'phone_code' => '+266', 'flag' => '🇱🇸', 'currency' => 'LSL'],
            ['country_code' => 'LR', 'countrie_name' => 'Libéria', 'phone_code' => '+231', 'flag' => '🇱🇷', 'currency' => 'LRD'],
            ['country_code' => 'LY', 'countrie_name' => 'Jamahiriya arabe libyenne', 'phone_code' => '+218', 'flag' => '🇱🇾', 'currency' => 'LYD'],
            ['country_code' => 'LI', 'countrie_name' => 'Liechtenstein', 'phone_code' => '+423', 'flag' => '🇱🇮', 'currency' => 'CHF'],
            ['country_code' => 'LT', 'countrie_name' => 'Lituanie', 'phone_code' => '+370', 'flag' => '🇱🇹', 'currency' => 'EUR'],
            ['country_code' => 'LU', 'countrie_name' => 'Luxembourg', 'phone_code' => '+352', 'flag' => '🇱🇺', 'currency' => 'EUR'],
            ['country_code' => 'MO', 'countrie_name' => 'Macau', 'phone_code' => '+853', 'flag' => '🇲🇴', 'currency' => 'MOP'],
            ['country_code' => 'MK', 'countrie_name' => 'Macédoine', 'phone_code' => '+389', 'flag' => '🇲🇰', 'currency' => 'MKD'],
            ['country_code' => 'MG', 'countrie_name' => 'Madagascar', 'phone_code' => '+261', 'flag' => '🇲🇬', 'currency' => 'MGA'],
            ['country_code' => 'MW', 'countrie_name' => 'Malawi', 'phone_code' => '+265', 'flag' => '🇲🇼', 'currency' => 'Kwacha'],
            ['country_code' => 'MY', 'countrie_name' => 'Malaisie', 'phone_code' => '+60', 'flag' => '🇲🇾', 'currency' => 'Ringgit'],
            ['country_code' => 'MV', 'countrie_name' => 'Maldives', 'phone_code' => '+960', 'flag' => '🇲🇻', 'currency' => 'Rufiyaa'],
            ['country_code' => 'MT', 'countrie_name' => 'Malte', 'phone_code' => '+356', 'flag' => '🇲🇹', 'currency' => 'Euro'],
            ['country_code' => 'MH', 'countrie_name' => 'Îles Marshall', 'phone_code' => '+692', 'flag' => '🇲🇭', 'currency' => 'Dollar des États-Unis'],
            ['country_code' => 'MQ', 'countrie_name' => 'Martinique', 'phone_code' => '+596', 'flag' => '🇲🇶', 'currency' => 'Euro'],
            ['country_code' => 'MR', 'countrie_name' => 'Mauritanie', 'phone_code' => '+222', 'flag' => '🇲🇷', 'currency' => 'Ouguiya'],
            ['country_code' => 'MU', 'countrie_name' => 'Île Maurice', 'phone_code' => '+230', 'flag' => '🇲🇺', 'currency' => 'Roupie'],
            ['country_code' => 'TY', 'countrie_name' => 'Mayotte', 'phone_code' => '+262', 'flag' => '🇾🇹', 'currency' => 'Euro'],
            ['country_code' => 'MX', 'countrie_name' => 'Mexique', 'phone_code' => '+52', 'flag' => '🇲🇽', 'currency' => 'Peso'],
            ['country_code' => 'FM', 'countrie_name' => 'Micronésie', 'phone_code' => '+691', 'flag' => '🇫🇲', 'currency' => 'Dollar des États-Unis'],
            ['country_code' => 'MD', 'countrie_name' => 'Moldavie', 'phone_code' => '+373', 'flag' => '🇲🇩', 'currency' => 'Leu'],
            ['country_code' => 'MC', 'countrie_name' => 'Monaco', 'phone_code' => '+377', 'flag' => '🇲🇨', 'currency' => 'Euro'],
            ['country_code' => 'MN', 'countrie_name' => 'Mongolie', 'phone_code' => '+976', 'flag' => '🇲🇳', 'currency' => 'Tugrik'],
            ['country_code' => 'MS', 'countrie_name' => 'Montserrat', 'phone_code' => '+1-664', 'flag' => '🇲🇸', 'currency' => 'Livre sterling'],
            ['country_code' => 'MA', 'countrie_name' => 'Maroc', 'phone_code' => '+212', 'flag' => '🇲🇦', 'currency' => 'Dirham'],
            ['country_code' => 'MZ', 'countrie_name' => 'Mozambique', 'phone_code' => '+258', 'flag' => '🇲🇿', 'currency' => 'Metical'],
            ['country_code' => 'MM', 'countrie_name' => 'Myanmar', 'phone_code' => '+95', 'flag' => '🇲🇲', 'currency' => 'Kyat'],
            ['country_code' => 'NA', 'countrie_name' => 'Namibie', 'phone_code' => '+264', 'flag' => '🇳🇦', 'currency' => 'Dollar namibien'],
            ['country_code' => 'NR', 'countrie_name' => 'Nauru', 'phone_code' => '+674', 'flag' => '🇳🇷', 'currency' => 'Dollar australien'],
            ['country_code' => 'NP', 'countrie_name' => 'Népal', 'phone_code' => '+977', 'flag' => '🇳🇵', 'currency' => 'Roupie népalaise'],
            ['country_code' => 'NL', 'countrie_name' => 'Pays-Bas', 'phone_code' => '+31', 'flag' => '🇳🇱', 'currency' => 'Euro'],
            ['country_code' => 'AN', 'countrie_name' => 'Antilles néerlandaises', 'phone_code' => '+599', 'flag' => '🇳🇱', 'currency' => 'Guilder'],
            ['country_code' => 'NC', 'countrie_name' => 'Nouvelle-Calédonie', 'phone_code' => '+687', 'flag' => '🇳🇨', 'currency' => 'Franc pacifique'],
            ['country_code' => 'NZ', 'countrie_name' => 'Nouvelle-Zélande', 'phone_code' => '+64', 'flag' => '🇳🇿', 'currency' => 'Dollar néo-zélandais'],
            ['country_code' => 'NI', 'countrie_name' => 'Nicaragua', 'phone_code' => '+505', 'flag' => '🇳🇮', 'currency' => 'Córdoba'],
            ['country_code' => 'NG', 'countrie_name' => 'Nigéria', 'phone_code' => '+234', 'flag' => '🇳🇬', 'currency' => 'Naira'],
            ['country_code' => 'NU', 'countrie_name' => 'Niue', 'phone_code' => '+683', 'flag' => '🇳🇺', 'currency' => 'Dollar néo-zélandais'],
            ['country_code' => 'NF', 'countrie_name' => 'Île Norfolk', 'phone_code' => '+672', 'flag' => '🇳🇫', 'currency' => 'Dollar australien'],
            ['country_code' => 'MP', 'countrie_name' => 'Îles Mariannes du Nord', 'phone_code' => '+1-670', 'flag' => '🇲🇵', 'currency' => 'Dollar des États-Unis'],
            ['country_code' => 'NO', 'countrie_name' => 'Norvège', 'phone_code' => '+47', 'flag' => '🇳🇴', 'currency' => 'Couronne norvégienne'],
            ['country_code' => 'OM', 'countrie_name' => 'Oman', 'phone_code' => '+968', 'flag' => '🇴🇲', 'currency' => 'Rial'],
            ['country_code' => 'PK', 'countrie_name' => 'Pakistan', 'phone_code' => '+92', 'flag' => '🇵🇰', 'currency' => 'Roupie pakistanaise'],
            ['country_code' => 'PW', 'countrie_name' => 'Palaos', 'phone_code' => '+680', 'flag' => '🇵🇼', 'currency' => 'Dollar des États-Unis'],
            ['country_code' => 'PA', 'countrie_name' => 'Panama', 'phone_code' => '+507', 'flag' => '🇵🇦', 'currency' => 'Balboa'],
            ['country_code' => 'PG', 'countrie_name' => 'Papouasie-Nouvelle-Guinée', 'phone_code' => '+675', 'flag' => '🇵🇬', 'currency' => 'Kina'],
            ['country_code' => 'PY', 'countrie_name' => 'Paraguay', 'phone_code' => '+595', 'flag' => '🇵🇾', 'currency' => 'Guarani'],
            ['country_code' => 'PE', 'countrie_name' => 'Pérou', 'phone_code' => '+51', 'flag' => '🇵🇪', 'currency' => 'Nuevo Sol'],
            ['country_code' => 'PH', 'countrie_name' => 'Philippines', 'phone_code' => '+63', 'flag' => '🇵🇭', 'currency' => 'Peso philippin'],
            ['country_code' => 'PN', 'countrie_name' => 'Îles Pitcairn', 'phone_code' => '+64', 'flag' => '🇵🇳', 'currency' => 'Livre sterling'],
            ['country_code' => 'PL', 'countrie_name' => 'Pologne', 'phone_code' => '+48', 'flag' => '🇵🇱', 'currency' => 'PLN'],
            ['country_code' => 'PF', 'countrie_name' => 'Polynésie française', 'phone_code' => '+689', 'flag' => '🇵🇫', 'currency' => 'XPF'],
            ['country_code' => 'PR', 'countrie_name' => 'Porto Rico', 'phone_code' => '+1-787', 'flag' => '🇵🇷', 'currency' => 'USD'],
            ['country_code' => 'PT', 'countrie_name' => 'Portugal', 'phone_code' => '+351', 'flag' => '🇵🇹', 'currency' => 'EUR'],
            ['country_code' => 'QA', 'countrie_name' => 'Qatar', 'phone_code' => '+974', 'flag' => '🇶🇦', 'currency' => 'QAR'],
            ['country_code' => 'SS', 'countrie_name' => 'République du Soudan du Sud', 'phone_code' => '+211', 'flag' => '🇸🇸', 'currency' => 'SSP'],
            ['country_code' => 'RE', 'countrie_name' => 'Réunion', 'phone_code' => '+262', 'flag' => '🇷🇪', 'currency' => 'EUR'],
            ['country_code' => 'RO', 'countrie_name' => 'Roumanie', 'phone_code' => '+40', 'flag' => '🇷🇴', 'currency' => 'RON'],
            ['country_code' => 'RU', 'countrie_name' => 'Fédération de Russie', 'phone_code' => '+7', 'flag' => '🇷🇺', 'currency' => 'RUB'],
            ['country_code' => 'RW', 'countrie_name' => 'Rwanda', 'phone_code' => '+250', 'flag' => '🇷🇼', 'currency' => 'RWF'],
            ['country_code' => 'KN', 'countrie_name' => 'Saint-Christophe-et-Niévès', 'phone_code' => '+1-869', 'flag' => '🇰🇳', 'currency' => 'XCD'],
            ['country_code' => 'LC', 'countrie_name' => 'Sainte-Lucie', 'phone_code' => '+1-758', 'flag' => '🇱🇨', 'currency' => 'XCD'],
            ['country_code' => 'VC', 'countrie_name' => 'Saint-Vincent-et-les-Grenadines', 'phone_code' => '+1-784', 'flag' => '🇻🇨', 'currency' => 'XCD'],
            ['country_code' => 'WS', 'countrie_name' => 'Samoa', 'phone_code' => '+685', 'flag' => '🇼🇸', 'currency' => 'WST'],
            ['country_code' => 'SM', 'countrie_name' => 'Saint-Marin', 'phone_code' => '+378', 'flag' => '🇸🇲', 'currency' => 'EUR'],
            ['country_code' => 'ST', 'countrie_name' => 'Sao Tomé-et-Principe', 'phone_code' => '+239', 'flag' => '🇸🇹', 'currency' => 'STN'],
            ['country_code' => 'SA', 'countrie_name' => 'Arabie Saoudite', 'phone_code' => '+966', 'flag' => '🇸🇦', 'currency' => 'SAR'],
            ['country_code' => 'SN', 'countrie_name' => 'Sénégal', 'phone_code' => '+221', 'flag' => '🇸🇳', 'currency' => 'XOF'],
            ['country_code' => 'RS', 'countrie_name' => 'Serbie', 'phone_code' => '+381', 'flag' => '🇷🇸', 'currency' => 'RSD'],
            ['country_code' => 'SC', 'countrie_name' => 'Seychelles', 'phone_code' => '+248', 'flag' => '🇸🇨', 'currency' => 'SCR'],
            ['country_code' => 'SL', 'countrie_name' => 'Sierra Leone', 'phone_code' => '+232', 'flag' => '🇸🇱', 'currency' => 'SLL'],
            ['country_code' => 'SG', 'countrie_name' => 'Singapour', 'phone_code' => '+65', 'flag' => '🇸🇬', 'currency' => 'SGD'],
            ['country_code' => 'SK', 'countrie_name' => 'Slovaquie', 'phone_code' => '+421', 'flag' => '🇸🇰', 'currency' => 'EUR'],
            ['country_code' => 'SI', 'countrie_name' => 'Slovénie', 'phone_code' => '+386', 'flag' => '🇸🇮', 'currency' => 'EUR'],
            ['country_code' => 'SB', 'countrie_name' => 'Îles Salomon', 'phone_code' => '+677', 'flag' => '🇸🇧', 'currency' => 'SBD'],
            ['country_code' => 'SO', 'countrie_name' => 'Somalie', 'phone_code' => '+252', 'flag' => '🇸🇴', 'currency' => 'SOS'],
            ['country_code' => 'ZA', 'countrie_name' => 'Afrique du Sud', 'phone_code' => '+27', 'flag' => '🇿🇦', 'currency' => 'ZAR'],
            ['country_code' => 'GS', 'countrie_name' => 'Géorgie du Sud-et-les îles Sandwich du Sud', 'phone_code' => '+500', 'flag' => '🇬🇸', 'currency' => 'GBP'],
            ['country_code' => 'ES', 'countrie_name' => 'Espagne', 'phone_code' => '+34', 'flag' => '🇪🇸', 'currency' => 'EUR'],
            ['country_code' => 'LK', 'countrie_name' => 'Sri Lanka', 'phone_code' => '+94', 'flag' => '🇱🇰', 'currency' => 'LKR'],
            ['country_code' => 'SH', 'countrie_name' => 'Sainte-Hélène', 'phone_code' => '+290', 'flag' => '🇸🇭', 'currency' => 'SHP'],
            ['country_code' => 'PM', 'countrie_name' => 'Saint-Pierre-et-Miquelon', 'phone_code' => '+508', 'flag' => '🇵🇲', 'currency' => 'EUR'],
            ['country_code' => 'SD', 'countrie_name' => 'Soudan', 'phone_code' => '+249', 'flag' => '🇸🇩', 'currency' => 'SDG'],
            ['country_code' => 'SR', 'countrie_name' => 'Suriname', 'phone_code' => '+597', 'flag' => '🇸🇷', 'currency' => 'SRD'],
            ['country_code' => 'SJ', 'countrie_name' => 'Îles Svalbard et Jan Mayen', 'phone_code' => '+47', 'flag' => '🇸🇯', 'currency' => 'NOK'],
            ['country_code' => 'SZ', 'countrie_name' => 'Eswatini', 'phone_code' => '+268', 'flag' => '🇸🇿', 'currency' => 'SZL'],
            ['country_code' => 'SE', 'countrie_name' => 'Suède', 'phone_code' => '+46', 'flag' => '🇸🇪', 'currency' => 'SEK'],
            ['country_code' => 'CH', 'countrie_name' => 'Suisse', 'phone_code' => '+41', 'flag' => '🇨🇭', 'currency' => 'CHF'],
            ['country_code' => 'SY', 'countrie_name' => 'République arabe syrienne', 'phone_code' => '+963', 'flag' => '🇸🇾', 'currency' => 'SYP'],
            ['country_code' => 'TW', 'countrie_name' => 'Taïwan', 'phone_code' => '+886', 'flag' => '🇹🇼', 'currency' => 'TWD'],
            ['country_code' => 'TJ', 'countrie_name' => 'Tadjikistan', 'phone_code' => '+992', 'flag' => '🇹🇯', 'currency' => 'TJS'],
            ['country_code' => 'TZ', 'countrie_name' => 'Tanzanie, République-Unie de', 'phone_code' => '+255', 'flag' => '🇹🇿', 'currency' => 'TZS'],
            ['country_code' => 'TH', 'countrie_name' => 'Thaïlande', 'phone_code' => '+66', 'flag' => '🇹🇭', 'currency' => 'THB'],
            ['country_code' => 'TG', 'countrie_name' => 'Togo', 'phone_code' => '+228', 'flag' => '🇹🇬', 'currency' => 'XOF'],
            ['country_code' => 'TK', 'countrie_name' => 'Tokelau', 'phone_code' => '+690', 'flag' => '🇹🇰', 'currency' => 'NZD'],
            ['country_code' => 'TO', 'countrie_name' => 'Tonga', 'phone_code' => '+676', 'flag' => '🇹🇴', 'currency' => 'TOP'],
            ['country_code' => 'TT', 'countrie_name' => 'Trinité-et-Tobago', 'phone_code' => '+1-868', 'flag' => '🇹🇹', 'currency' => 'TTD'],
            ['country_code' => 'TN', 'countrie_name' => 'Tunisie', 'phone_code' => '+216', 'flag' => '🇹🇳', 'currency' => 'TND'],
            ['country_code' => 'TM', 'countrie_name' => 'Turkménistan', 'phone_code' => '+993', 'flag' => '🇹🇲', 'currency' => 'TMT'],
            ['country_code' => 'TR', 'countrie_name' => 'Turquie', 'phone_code' => '+90', 'flag' => '🇹🇷', 'currency' => 'TRY'],
            ['country_code' => 'TC', 'countrie_name' => 'Îles Turques-et-Caïques', 'phone_code' => '+1-649', 'flag' => '🇹🇨', 'currency' => 'XCD'],
            ['country_code' => 'TV', 'countrie_name' => 'Tuvalu', 'phone_code' => '+688', 'flag' => '🇹🇻', 'currency' => 'AUD'],
            ['country_code' => 'UG', 'countrie_name' => 'Ouganda', 'phone_code' => '+256', 'flag' => '🇺🇬', 'currency' => 'UGX'],
            ['country_code' => 'UA', 'countrie_name' => 'Ukraine', 'phone_code' => '+380', 'flag' => '🇺🇦', 'currency' => 'UAH'],
            ['country_code' => 'AE', 'countrie_name' => 'Émirats arabes unis', 'phone_code' => '+971', 'flag' => '🇦🇪', 'currency' => 'AED'],
            ['country_code' => 'GB', 'countrie_name' => 'Royaume-Uni', 'phone_code' => '+44', 'flag' => '🇬🇧', 'currency' => 'GBP'],
            ['country_code' => 'US', 'countrie_name' => 'États-Unis d\'Amérique', 'phone_code' => '+1', 'flag' => '🇺🇸', 'currency' => 'USD'],
            ['country_code' => 'UY', 'countrie_name' => 'Uruguay', 'phone_code' => '+598', 'flag' => '🇺🇾', 'currency' => 'UYU'],
            ['country_code' => 'UZ', 'countrie_name' => 'Ouzbékistan', 'phone_code' => '+998', 'flag' => '🇺🇿', 'currency' => 'UZS'],
            ['country_code' => 'VU', 'countrie_name' => 'Vanuatu', 'phone_code' => '+678', 'flag' => '🇻🇺', 'currency' => 'VUV'],
            ['country_code' => 'VE', 'countrie_name' => 'Venezuela', 'phone_code' => '+58', 'flag' => '🇻🇪', 'currency' => 'VEF'],
            ['country_code' => 'VN', 'countrie_name' => 'Vietnam', 'phone_code' => '+84', 'flag' => '🇻🇳', 'currency' => 'VND'],
            ['country_code' => 'WF', 'countrie_name' => 'Wallis-et-Futuna', 'phone_code' => '+681', 'flag' => '🇼🇫', 'currency' => 'XPF'],
            ['country_code' => 'YE', 'countrie_name' => 'Yémen', 'phone_code' => '+967', 'flag' => '🇾🇪', 'currency' => 'YER'],
            ['country_code' => 'ZM', 'countrie_name' => 'Zambie', 'phone_code' => '+260', 'flag' => '🇿🇲', 'currency' => 'ZMK'],
            ['country_code' => 'ZW', 'countrie_name' => 'Zimbabwe', 'phone_code' => '+263', 'flag' => '🇿🇼', 'currency' => 'ZWL']


        ];

        DB::table('full_countrie_models')->insert($countries_data);

    }
}
